HOLDINGS="ASTINO DUFU GKENT MUDA N2N NOTION PADINI PETRONM"
WATCHLIST="AEMULUS BONIA ECS HAIO HENGYUAN KGB LAYHONG MBSB MKH MMODE PADINI PETRONM SAMCHEM SCGM GCB"
MOMENTUM="BCMALL CHINWEL DANCO FLBHD KOBAY ORIENT YSPSAH"
DIVIDEND="FPI LCTITAN MAGNI UCHITEC KMLOONG MPI DUFU TONGHER CSCSTEL LIHEN TGUAN CHOOBEE GADANG OKA POHUAT PECCA SURIA"
MVP="DUFU PADINI PETRONM KLSE MAGNI"
GENISTA="APEX BURSA CBIP CIMB HIBISCS IOICORP IOIPG IVORY KPS PCHEM PRESBHD RSENA"
SNIPER="UCREST YONGTAI NGGB"
DATA=/z/data

TEST=$MVP
STARTDT="2012-01-03"
ENDDT="2018-12-13"

for i in $TEST
do
 echo Profiling $i
 ${DATA}/mpv/simulation/profiling/newprofiling2.sh $i ${STARTDT}:${ENDDT}:3
done

for i in $TEST
do
 echo Charting $i
 ${DATA}/mpv/simulation/profiling/charting.sh $i ${STARTDT}:${ENDDT}
done
