HOLDINGS="ASTINO DUFU GKENT MUDA N2N NOTION PADINI PETRONM"
WATCHLIST="AEMULUS BONIA ECS HAIO HENGYUAN KGB LAYHONG MBSB MKH MMODE PADINI PETRONM SAMCHEM SCGM GCB"
MOMENTUM="BCMALL CHINWEL DANCO FLBHD KOBAY ORIENT YSPSAH"
DIVIDEND="FPI LCTITAN MAGNI UCHITEC KMLOONG MPI DUFU TONGHER CSCSTEL LIHEN TGUAN CHOOBEE GADANG OKA POHUAT PECCA SURIA"
MVP="DUFU PADINI PETRONM"
GENISTA="APEX BURSA CBIP CIMB HIBISCS IOICORP IOIPG IVORY KPS PCHEM PRESBHD RSENA"
SNIPER="UCREST YONGTAI NGGB"
for i in $MVP
do
 echo $i
 ./scripts/newprofiling.sh $i 2011-10-03:2018-11-30:3
done
