HOLDINGS="ASTINO DUFU GKENT MUDA N2N NOTION PADINI PETRONM"
WATCHLIST="AEMULUS BONIA ECS HAIO HENGYUAN KGB LAYHONG MBSB MKH MMODE PADINI PETRONM SAMCHEM SCGM GCB"
MOMENTUM="BCMALL CHINWEL DANCO FLBHD KOBAY ORIENT YSPSAH"
DIVIDEND="FPI LCTITAN MAGNI UCHITEC KMLOONG MPI DUFU TONGHER CSCSTEL LIHEN TGUAN CHOOBEE GADANG OKA POHUAT PECCA SURIA"
MVP="DUFU PADINI PETRONM KLSE MAGNI"
GENISTA="APEX BURSA CBIP CIMB HIBISCS IOICORP IOIPG IVORY KPS PCHEM PRESBHD RSENA"
SNIPER="UCREST YONGTAI NGGB"

TEST=$MVP
STARTDT="2011-09-03"
ENDDT="2018-12-13"

for i in $TEST
do
 echo Profiling $i
 ./scripts/newprofiling2.sh $i ${STARTDT}:${ENDDT}:3
 echo Charting $i
 ./scripts/charting.sh $i ${STARTDT}:${ENDDT}
done
